"""Versioned simulator boundary matching the authenticated forty-task baseline."""
import numpy as np


def execution_chunk_float32(raw_actions):
    """Round once BEFORE gripper processing; never mutate raw policy outputs."""
    raw = np.asarray(raw_actions)
    if raw.shape != (8, 7) or raw.dtype.kind != "f" or not np.isfinite(raw).all():
        raise ValueError("expected finite floating-point 8x7 action chunk")
    with np.errstate(over="ignore", invalid="ignore"):
        result = np.array(raw, dtype=np.float32, copy=True)
    if not np.isfinite(result).all():
        raise ValueError("action conversion overflow")
    return result


def processed_command_chunk(raw_actions, process_action, model_family):
    """Diagnostic copy of the commands generated by the verified episode loop."""
    rounded = execution_chunk_float32(raw_actions)
    commands = np.stack([np.asarray(process_action(row.copy(), model_family)) for row in rounded])
    if commands.shape != (8, 7) or commands.dtype != np.float32 or not np.isfinite(commands).all():
        raise ValueError("processed command contract differs")
    return commands
